'use client';
import { AppShell } from '@/components/app-shell';
import { AuctionSetup } from '@/components/auction-setup';
import { Check, Copy, Crown, Plus, UsersRound } from 'lucide-react';
import { FormEvent, useEffect, useState } from 'react';

type Manager = { id: string; display_name: string; is_admin: boolean; squads: { name: string; budget: number }[] };
export default function ManagersPage() {
  const [managers, setManagers] = useState<Manager[]>([]), [loading,setLoading]=useState(true), [message,setMessage]=useState(''), [password,setPassword]=useState('');
  const [form,setForm]=useState({ name:'', email:'', teamName:'', commissionerCode:'', isAdmin:false });
  useEffect(()=>{fetch('/api/admin/managers').then(r=>r.json()).then(d=>setManagers(d.managers||[])).finally(()=>setLoading(false));},[]);
  async function addManager(e: FormEvent){e.preventDefault();setMessage('');setPassword('');const res=await fetch('/api/admin/managers',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const data=await res.json();if(!res.ok){setMessage(data.error||'Something went wrong.');return;}setManagers(current=>[...current,{...data.manager,squads:[data.manager.squad]}]);setPassword(data.temporaryPassword);setMessage(`${form.name} is ready to join.`);setForm(current=>({...current,name:'',email:'',teamName:'',isAdmin:false}));}
  return <AppShell><section className="page-heading admin-heading"><div><p className="eyebrow">Commissioner tools</p><h1>Manage your league.</h1><p className="sub">Create managers, then enter their completed offline-auction squads.</p></div><div className="manager-count"><UsersRound/><strong>{managers.length} <small>/ 18 managers</small></strong></div></section>
  <section className="manager-grid"><div className="panel add-manager"><h2><Plus size={19}/> Add a manager</h2><form onSubmit={addManager}><div className="two-fields"><label className="field">Manager name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="e.g. Maya Cole"/></label><label className="field">Team name<input required value={form.teamName} onChange={e=>setForm({...form,teamName:e.target.value})} placeholder="e.g. The Gaffers"/></label></div><label className="field">Email address<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="manager@email.com"/></label><label className="field">Commissioner code<input required type="password" value={form.commissionerCode} onChange={e=>setForm({...form,commissionerCode:e.target.value})} placeholder="Set in your Vercel settings"/></label><label className="checkbox"><input type="checkbox" checked={form.isAdmin} onChange={e=>setForm({...form,isAdmin:e.target.checked})}/><span>Give this manager commissioner access</span></label><button className="primary" type="submit"><Plus size={17}/> Create manager</button></form>{message&&<div className={password?'success':'form-error'}>{password?<><Check size={17}/>{message}<span>Temporary password: <b>{password}</b></span><button onClick={()=>navigator.clipboard.writeText(password)}><Copy size={14}/> Copy</button></>:message}</div>}</div>
  <div className="panel managers-list"><div className="section-head"><div><p className="eyebrow">Your people</p><h2>Managers</h2></div></div>{loading?<p className="helper">Loading managers…</p>:managers.length===0?<div className="empty-state"><UsersRound/><strong>No managers yet</strong><span>Create your first manager on the left.</span></div>:managers.map(m=><div className="manager-item" key={m.id}><div className="manager-avatar">{m.display_name.slice(0,1)}</div><div><strong>{m.display_name} {m.is_admin&&<Crown size={13}/>}</strong><small>{m.squads?.[0]?.name||'Team pending'}</small></div><span>£{((m.squads?.[0]?.budget||0)/10).toFixed(1)}m</span></div>)}</div></section><AuctionSetup/></AppShell>;
}
