'use client';
import { AppShell } from '@/components/app-shell';
import { Search, SlidersHorizontal } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';

type Player = { id:number; name:string; team:string; position:string; price:number; owner:string|null; points:number; starts:number; cleanSheets:number; defensiveContribution:number; assists:number; goals:number; penaltiesMissed:number; penaltiesSaved:number; yellowCards:number; redCards:number };
const columns: { key: keyof Player; label: string }[] = [{key:'points',label:'Pts'}, {key:'starts',label:'Starts'}, {key:'cleanSheets',label:'CS'}, {key:'defensiveContribution',label:'Def con.'}, {key:'assists',label:'A'}, {key:'goals',label:'G'}, {key:'penaltiesMissed',label:'Pen miss'}, {key:'penaltiesSaved',label:'Pen save'}, {key:'yellowCards',label:'YC'}, {key:'redCards',label:'RC'}];

export default function PlayersPage(){
 const [players,setPlayers]=useState<Player[]>([]), [loading,setLoading]=useState(true), [error,setError]=useState(''); const [search,setSearch]=useState(''), [position,setPosition]=useState('All'), [ownership,setOwnership]=useState('All'), [sort,setSort]=useState<keyof Player>('points');
 useEffect(()=>{fetch('/api/players').then(async r=>{const data=await r.json();if(!r.ok)throw new Error(data.error);setPlayers(data.players||[])}).catch(e=>setError(e.message||'Unable to load the FPL player list.')).finally(()=>setLoading(false));},[]);
 const filtered=useMemo(()=>players.filter(p=>(position==='All'||p.position===position)&&(ownership==='All'||(ownership==='Available'?!p.owner:!!p.owner))&&`${p.name} ${p.team}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>Number(b[sort])-Number(a[sort])||a.name.localeCompare(b.name)),[players,search,position,ownership,sort]);
 return <AppShell><section className="page-heading"><p className="eyebrow">Official FPL data</p><h1>The player market.</h1><p className="sub">Season totals mirror FPL scoring without bonus points, captaincy or chips.</p></section>
 <section className="filters"><label><Search size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search players or teams"/></label><div className="selects"><select value={position} onChange={e=>setPosition(e.target.value)}><option>All</option><option>GK</option><option>DEF</option><option>MID</option><option>FWD</option></select><select value={ownership} onChange={e=>setOwnership(e.target.value)}><option>All</option><option>Available</option><option>Owned</option></select><button><SlidersHorizontal size={16}/> {players.length || '—'} players</button></div></section>
 <section className="panel player-table player-market">{loading?<p className="table-message">Loading the official FPL player list…</p>:error?<p className="form-error">{error}</p>:<div className="market-scroll"><div className="market-head"><span>Player</span><span>Pos.</span><span>Price</span><span>Owner</span>{columns.map(c=><button key={c.key} onClick={()=>setSort(c.key)} className={sort===c.key?'sorted':''}>{c.label}</button>)}</div>{filtered.map(p=><div className="market-row" key={p.id}><div><strong>{p.name}</strong><small>{p.team}</small></div><span className={`position-chip ${p.position.toLowerCase()}`}>{p.position}</span><span>£{(p.price/10).toFixed(1)}m</span><span className={p.owner?'owner':'available'}>{p.owner||'Available'}</span>{columns.map(c=><strong key={c.key}>{p[c.key] as number}</strong>)}</div>)}</div>}</section></AppShell>
}
