'use client';
import { AppShell } from '@/components/app-shell';
import { standings as demoStandings } from '@/lib/demo-data';
import { ArrowUpRight, CalendarDays, ChevronRight, Trophy } from 'lucide-react';
import Link from 'next/link';
import { teamSlug } from '@/lib/teams';
import { useEffect, useState } from 'react';
type Standing = { rank:number; name:string; manager:string; points:number; week:number; change:string };
export default function LeaguePage() {
 const [standings,setStandings]=useState<Standing[]>(demoStandings);
 useEffect(()=>{fetch('/api/standings').then(r=>r.json()).then(data=>{if(data.standings?.length)setStandings(data.standings)}).catch(()=>undefined);},[]);
 return <AppShell><section className="hero hero-premium"><div className="hero-copy"><p className="eyebrow">Private league · Season 2025 / 26</p><h1>Bails &amp; Goldies<br/><i>Fantasy Football</i></h1><p className="sub">Gameweek 12 is live. Your latest league position and scores are below.</p><div className="hero-meta"><span><i/> LIVE NOW</span><span>Official FPL data</span></div></div><div className="gw-card score-card"><span>Current gameweek</span><strong>LIVE</strong><div className="score-rule"/><p>League managers <b>{standings.length}</b></p><em>Custom scoring active</em></div></section><section className="dashboard-grid"><div className="panel standings"><div className="section-head"><div><p className="eyebrow">The championship</p><h2>League table</h2></div><button>Full table <ChevronRight size={16}/></button></div><div className="table-head"><span>#</span><span>Team</span><span>GW</span><span>Total</span></div>{standings.map(row=><div className={'standing '+(row.rank===1?'leader':'')} key={row.name}><b>{String(row.rank).padStart(2,'0')}</b><div><Link className="team-link" href={`/team/${teamSlug(row.name)}`}>{row.name}</Link><small>{row.manager} <em>{row.change}</em></small></div><span>{row.week}</span><strong>{row.points}</strong></div>)}</div><aside className="side-stack"><div className="panel next"><p className="eyebrow">Next up</p><h2>Transfer window</h2><p>Opens Friday at 18:00<br/>Closes Saturday at 11:30</p><a href="/transfers">Enter the room <ArrowUpRight size={15}/></a></div><div className="panel scoring"><Trophy size={19}/><div><p className="eyebrow">The rulebook</p><strong>Custom scoring</strong><small>FPL scoring, without bonus or captains</small></div></div></aside></section><section className="panel match-card"><div><p className="eyebrow">Gameweek head-to-head</p><h2>Scores update from official FPL data</h2><p><CalendarDays size={15}/> Scores lock Monday, 22:00</p></div><div className="match-score"><strong>FPL</strong><span>—</span><strong className="muted">LIVE</strong></div></section></AppShell>;
}
