'use client';
import { FormEvent, useEffect, useState } from 'react';
import { Upload } from 'lucide-react';
type Manager = { id: string; display_name: string; squads: { name: string; budget: number }[] };
type PlayerOption = { id: number; label: string };
const blank = Array.from({ length: 11 }, () => ({ player: '', price: '0' }));
export function AuctionSetup() {
 const [managers,setManagers]=useState<Manager[]>([]), [playerOptions,setPlayerOptions]=useState<PlayerOption[]>([]), [managerId,setManagerId]=useState(''), [code,setCode]=useState(''), [entries,setEntries]=useState(blank), [message,setMessage]=useState(''), [saving,setSaving]=useState(false);
 async function loadPlayers(){const data=await fetch('/api/players').then(r=>r.json());setPlayerOptions((data.players||[]).map((player:any)=>({id:player.id,label:`${player.fullName} · ${player.team} (${player.position})`})));}
 useEffect(()=>{fetch('/api/admin/managers').then(r=>r.json()).then(data=>setManagers(data.managers||[]));loadPlayers();},[]);
 const spend=entries.reduce((sum,row)=>sum+(Number(row.price)||0),0);
 async function submit(e:FormEvent){e.preventDefault();setMessage('');setSaving(true);const optionMap=new Map(playerOptions.map(option=>[option.label,option.id]));const payload={commissionerCode:code,managerId,entries:entries.map(e=>({fplId:optionMap.get(e.player),price:Math.round(Number(e.price)*10)}))};const res=await fetch('/api/admin/auction-squad',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await res.json();setSaving(false);setMessage(res.ok?`Saved 11 players. £${(data.balance/10).toFixed(1)}m remains.`:data.error||`Unable to save squad (server returned ${res.status}).`);}
 async function sync(){setMessage('');setSaving(true);const res=await fetch('/api/admin/sync',{method:'POST',headers:{'x-commissioner-code':code}});const data=await res.json();setSaving(false);if(res.ok){setMessage(`FPL list updated: ${data.synced} players.`);loadPlayers();}else setMessage(data.error||'Unable to sync FPL players.');}
 return <section className="panel auction-setup"><div><p className="eyebrow">Offline auction</p><h2>Enter a completed squad</h2><p className="helper">Search by full player name and club, then enter prices in whole £1m increments. £0m is valid.</p></div><form onSubmit={submit}><datalist id="fpl-player-names">{playerOptions.map(option=><option key={option.id} value={option.label}/>)}</datalist><div className="auction-controls"><select required value={managerId} onChange={e=>setManagerId(e.target.value)}><option value="">Select manager</option>{managers.map(manager=><option value={manager.id} key={manager.id}>{manager.display_name} · {manager.squads?.[0]?.name}</option>)}</select><input required type="password" value={code} onChange={e=>setCode(e.target.value)} placeholder="Commissioner code"/></div><div className="auction-grid"><b>Player — full name and club</b><b>Price (£m)</b>{entries.map((entry,index)=><div className="auction-row" key={index}><input required list="fpl-player-names" value={entry.player} onChange={e=>setEntries(rows=>rows.map((row,i)=>i===index?{...row,player:e.target.value}:row))} placeholder={playerOptions.length?'Start typing a full player name':'Loading FPL player list…'}/><input required min="0" step="1" type="number" value={entry.price} onChange={e=>setEntries(rows=>rows.map((row,i)=>i===index?{...row,price:e.target.value}:row))} placeholder="0"/></div>)}</div><div className="auction-footer"><span>Spend <b>£{spend.toFixed(1)}m</b> · Remaining <b>£{(100-spend).toFixed(1)}m</b></span><div className="auction-actions"><button className="secondary" type="button" onClick={sync} disabled={saving}>Refresh FPL list</button><button className="primary" disabled={saving}><Upload size={16}/>{saving?'Saving…':'Save auction squad'}</button></div></div>{message&&<p className={message.startsWith('Saved')||message.startsWith('FPL')?'success':'form-error'}>{message}</p>}</form></section>;
}
