import { NextRequest, NextResponse } from 'next/server';
import { supabaseAdmin } from '@/lib/supabase-admin';
import { commissionerFromRequest } from '@/lib/api-auth';

const start = new Date('2026-01-01T00:30:00.000Z');
const schedule = (ids:string[], double:boolean) => { const pool = ids.length % 2 ? [...ids, 'bye'] : [...ids]; const rounds:any[]=[]; for(let round=0;round<pool.length-1;round++){ for(let i=0;i<pool.length/2;i++){ const a=pool[i], b=pool[pool.length-1-i]; if(a!=='bye'&&b!=='bye') rounds.push({round:round+1,home_squad_id:round%2?a:b,away_squad_id:round%2?b:a}); } pool.splice(1,0,pool.pop()!); } return double ? [...rounds,...rounds.map(row=>({ ...row,round:row.round+pool.length-1,home_squad_id:row.away_squad_id,away_squad_id:row.home_squad_id }))] : rounds; };

export async function GET(){try{const db=supabaseAdmin();const {data:league}=await db.from('leagues').select('id').limit(1).single();if(!league)throw new Error('League unavailable');const {data:cup}=await db.from('cup_competitions').select('id').eq('league_id',league.id).eq('season','2025/26').maybeSingle();if(!cup)return NextResponse.json({cup:null});const {data:divisions}=await db.from('cup_divisions').select('id,name,sort_order,cup_entries(squad_id,seed,squads(name,manager_id,profiles(display_name))),cup_fixtures(id,round_number,home_squad_id,away_squad_id,starts_at,ends_at)').eq('competition_id',cup.id).order('sort_order');return NextResponse.json({cup,divisions:divisions||[]});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:'Unable to load cups.'},{status:500});}}

export async function POST(request:NextRequest){const commissioner=await commissionerFromRequest(request);if(!commissioner?.leagueId)return NextResponse.json({error:'Commissioner access is required.'},{status:403});try{const db=supabaseAdmin();const {data:existing,error:existingError}=await db.from('cup_competitions').select('id').eq('league_id',commissioner.leagueId).eq('season','2025/26').maybeSingle();if(existingError)throw existingError;if(existing)return NextResponse.json({error:'Cups have already been generated.'},{status:409});const [{data:squads,error:squadError},{data:scores,error:scoreError}]=await Promise.all([db.from('squads').select('id,name,manager_id').eq('league_id',commissioner.leagueId),db.from('gameweek_scores').select('manager_id,total_points,gameweek').eq('league_id',commissioner.leagueId).lte('gameweek',19)]);if(squadError)throw squadError;if(scoreError)throw scoreError;const pointsByManager=new Map<string,number>();for(const score of scores||[])pointsByManager.set(score.manager_id,Math.max(pointsByManager.get(score.manager_id)||0,Number(score.total_points||0)));const ranked=(squads||[]).map((s:any)=>({...s,points:pointsByManager.get(s.manager_id)||0})).sort((a:any,b:any)=>b.points-a.points||a.name.localeCompare(b.name));if(ranked.length<2)return NextResponse.json({error:'Add at least two managers before generating cups.'},{status:400});const names=ranked.length<=10?['Olivier Giroud','Ian Dowie']:['Olivier Giroud','James Milner','Ian Dowie'];const sizes=names.map((_,i)=>Math.floor(ranked.length/names.length)+(i<ranked.length%names.length?1:0));const {data:cup,error:cupError}=await db.from('cup_competitions').insert({league_id:commissioner.leagueId,season:'2025/26'}).select().single();if(cupError)throw cupError;let offset=0;for(let i=0;i<names.length;i++){const group=ranked.slice(offset,offset+sizes[i]);offset+=sizes[i];const {data:division,error:divisionError}=await db.from('cup_divisions').insert({competition_id:cup.id,name:names[i],sort_order:i}).select().single();if(divisionError)throw divisionError;const {error:entryError}=await db.from('cup_entries').insert(group.map((s:any,index:number)=>({division_id:division.id,squad_id:s.id,seed:index+1})));if(entryError)throw entryError;const fixtures=schedule(group.map((s:any)=>s.id),group.length<=4).map((f:any,index:number)=>({ ...f,division_id:division.id,starts_at:new Date(start.getTime()+index*604800000).toISOString(),ends_at:new Date(start.getTime()+(index+1)*604800000).toISOString()}));if(fixtures.length){const {error:fixtureError}=await db.from('cup_fixtures').insert(fixtures);if(fixtureError)throw fixtureError;}}return NextResponse.json({generated:true});}catch(error){const detail=error&&typeof error==='object'&&'message' in error?String((error as {message:string}).message):'Unknown database error';return NextResponse.json({error:`Unable to generate cups: ${detail}`},{status:500});}}
