import { NextRequest, NextResponse } from 'next/server';
import { supabaseAdmin } from '@/lib/supabase-admin';
import { commissionerFromRequest } from '@/lib/api-auth';
import { cupTable, scoreCupFixtures } from '@/lib/cup-scoring';
import { cupSeedingRows } from '@/lib/cup-seeding';

const start=new Date('2026-01-01T00:30:00.000Z');
const schedule=(ids:string[],double:boolean)=>{const pool=ids.length%2?[...ids,'bye']:[...ids],out:any[]=[];for(let r=0;r<pool.length-1;r++){for(let i=0;i<pool.length/2;i++){const a=pool[i],b=pool[pool.length-1-i];if(a!=='bye'&&b!=='bye')out.push({round_number:r+1,home_squad_id:r%2?a:b,away_squad_id:r%2?b:a});}pool.splice(1,0,pool.pop()!);}return double?[...out,...out.map(row=>({...row,round_number:row.round_number+pool.length-1,home_squad_id:row.away_squad_id,away_squad_id:row.home_squad_id}))]:out;};

export async function GET(){try{const db=supabaseAdmin();const {data:league,error:leagueError}=await db.from('leagues').select('id').limit(1).single();if(leagueError)throw leagueError;const {data:cup,error:cupError}=await db.from('cup_competitions').select('id').eq('league_id',league.id).eq('season','2025/26').maybeSingle();if(cupError)throw cupError;if(!cup)return NextResponse.json({cup:null});const [{data:divisions,error:divisionError},{data:entries,error:entryError},{data:fixtures,error:fixtureError},{data:squads,error:squadError},{data:profiles,error:profileError}]=await Promise.all([db.from('cup_divisions').select('id,name,sort_order').eq('competition_id',cup.id).order('sort_order'),db.from('cup_entries').select('division_id,squad_id,seed'),db.from('cup_fixtures').select('*'),db.from('squads').select('id,name,manager_id'),db.from('profiles').select('id,display_name')]);if(divisionError||entryError||fixtureError||squadError||profileError)throw divisionError||entryError||fixtureError||squadError||profileError;const scoreMap=await scoreCupFixtures((fixtures||[]) as any);const squadMap=new Map((squads||[]).map((s:any)=>[s.id,s]));const profileMap=new Map((profiles||[]).map((p:any)=>[p.id,p.display_name]));const output=(divisions||[]).map((division:any)=>{const divisionEntries=(entries||[]).filter((e:any)=>e.division_id===division.id).map((e:any)=>({ ...e,team:squadMap.get(e.squad_id)?.name||'Team',manager:profileMap.get(squadMap.get(e.squad_id)?.manager_id)||'Manager'}));const divisionFixtures=(fixtures||[]).filter((f:any)=>f.division_id===division.id).map((f:any)=>({...f,score:scoreMap.get(f.id)||{home:0,away:0}}));return {...division,entries:divisionEntries,fixtures:divisionFixtures,table:cupTable(divisionEntries,divisionFixtures,scoreMap),playoff:divisionEntries.length>=5};});return NextResponse.json({cup,divisions:output});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:'Unable to load cups.'},{status:500});}}

export async function POST(request:NextRequest){const commissioner=await commissionerFromRequest(request);if(!commissioner?.leagueId)return NextResponse.json({error:'Commissioner access is required.'},{status:403});if(Date.now()<start.getTime())return NextResponse.json({error:'The cups cannot be processed till half way through the season.'},{status:400});try{const db=supabaseAdmin();const {data:existing}=await db.from('cup_competitions').select('id').eq('league_id',commissioner.leagueId).eq('season','2025/26').maybeSingle();if(existing)return NextResponse.json({error:'Cups have already been generated.'},{status:409});const {data:squads,error:squadError}=await db.from('squads').select('id').eq('league_id',commissioner.leagueId);if(squadError)throw squadError;const squadIds=new Set((squads||[]).map((s:any)=>s.id));const ranked=(await cupSeedingRows()).filter(row=>squadIds.has(row.id));if(ranked.length<2)return NextResponse.json({error:'Add at least two managers before generating cups.'},{status:400});const names=ranked.length<=10?['Olivier Giroud','Ian Dowie']:['Olivier Giroud','James Milner','Ian Dowie'];const sizes=names.map((_,i)=>Math.floor(ranked.length/names.length)+(i<ranked.length%names.length?1:0));const {data:cup,error:cupError}=await db.from('cup_competitions').insert({league_id:commissioner.leagueId,season:'2025/26'}).select().single();if(cupError)throw cupError;let offset=0;for(let i=0;i<names.length;i++){const group=ranked.slice(offset,offset+sizes[i]);offset+=sizes[i];const {data:division,error:divisionError}=await db.from('cup_divisions').insert({competition_id:cup.id,name:names[i],sort_order:i}).select().single();if(divisionError)throw divisionError;const {error:entryError}=await db.from('cup_entries').insert(group.map(s=>({division_id:division.id,squad_id:s.id,seed:s.rank})));if(entryError)throw entryError;const rows=schedule(group.map(s=>s.id),group.length<=4).map((row:any,index:number)=>({...row,division_id:division.id,starts_at:new Date(start.getTime()+index*604800000).toISOString(),ends_at:new Date(start.getTime()+(index+1)*604800000).toISOString()}));if(rows.length){const {error}=await db.from('cup_fixtures').insert(rows);if(error)throw error;}}return NextResponse.json({generated:true});}catch(error){return NextResponse.json({error:`Unable to generate cups: ${error instanceof Error?error.message:'Unknown database error'}`},{status:500});}}

export async function PATCH(request:NextRequest){const commissioner=await commissionerFromRequest(request);if(!commissioner?.leagueId)return NextResponse.json({error:'Commissioner access is required.'},{status:403});const {fixtureId,date}=await request.json();if(!fixtureId||!/^\d{4}-\d{2}-\d{2}$/.test(date||''))return NextResponse.json({error:'Choose a valid fixture date.'},{status:400});try{const db=supabaseAdmin();const {data:fixture,error:fixtureError}=await db.from('cup_fixtures').select('division_id').eq('id',fixtureId).single();if(fixtureError)throw fixtureError;const {data:division,error:divisionError}=await db.from('cup_divisions').select('competition_id').eq('id',fixture.division_id).single();if(divisionError)throw divisionError;const {data:cup,error:cupError}=await db.from('cup_competitions').select('league_id').eq('id',division.competition_id).single();if(cupError)throw cupError;if(cup.league_id!==commissioner.leagueId)return NextResponse.json({error:'This fixture belongs to another league.'},{status:403});const startsAt=new Date(`${date}T00:30:00.000Z`),endsAt=new Date(startsAt.getTime()+604800000);const {error}=await db.from('cup_fixtures').update({starts_at:startsAt.toISOString(),ends_at:endsAt.toISOString()}).eq('id',fixtureId);if(error)throw error;return NextResponse.json({saved:true});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:'Unable to update fixture date.'},{status:500});}}
