import { supabaseAdmin } from '@/lib/supabase-admin';

type Period='season'|'week'|'month';
type FixtureStat={fpl_id:number;gameweek:number;kickoff_at:string;points_excluding_bonus:number;goals:number;assists:number;clean_sheets:number};
type PeriodOption={key:string;label:string;start:string;end:string};
const monthNames=['August','September','October','November','December','January','February','March','April','May'];
const months:PeriodOption[]=monthNames.map((name,index)=>{const year=index<5?2025:2026;const month=index<5?7+index:index-5;const start=new Date(Date.UTC(year,month,1));const end=new Date(Date.UTC(year,month+1,1));return{key:`${year}-${String(month+1).padStart(2,'0')}`,label:`${name} ${year}`,start:start.toISOString(),end:end.toISOString()};});
// Tuesday 12 August 2025, 06:00 London (05:00 UTC during British Summer Time).
const weeks:PeriodOption[]=Array.from({length:42},(_,index)=>{const start=new Date(Date.parse('2025-08-12T05:00:00.000Z')+index*7*24*60*60*1000);const end=new Date(start.getTime()+7*24*60*60*1000);return{key:String(index+1),label:`Week ${index+1} · ${start.toLocaleDateString('en-GB',{day:'numeric',month:'short',timeZone:'Europe/London'})} – ${new Date(end.getTime()-1).toLocaleDateString('en-GB',{day:'numeric',month:'short',timeZone:'Europe/London'})}`,start:start.toISOString(),end:end.toISOString()};});
const emptyRow=(squad:any,profiles:Map<string,any>)=>({id:squad.id,manager:profiles.get(squad.manager_id)?.display_name||'Manager',team:squad.name,points:0,goals:0,assists:0,cleanSheets:0,weekPoints:0,monthPoints:0});
const ranked=(totals:Map<string,any>)=>[...totals.values()].sort((a,b)=>b.points-a.points||a.team.localeCompare(b.team)).map((row,index)=>({...row,rank:index+1}));
export async function scoreBoard(period:Period='season',key?:string){const db=supabaseAdmin();const [{data:memberships,error:membershipsError},{data:squads,error:squadsError},{data:profiles,error:profilesError},{data:players,error:playersError}]=await Promise.all([db.from('squad_players').select('squad_id,fpl_id,acquired_at,released_at'),db.from('squads').select('id,name,manager_id'),db.from('profiles').select('id,display_name'),db.from('fpl_players').select('fpl_id,raw')]);if(membershipsError)throw membershipsError;if(squadsError)throw squadsError;if(profilesError)throw profilesError;if(playersError)throw playersError;const playerIds=[...new Set((memberships||[]).map((membership:any)=>membership.fpl_id))];const {count,error:countError}=playerIds.length?await db.from('fpl_fixture_player_stats').select('*',{count:'exact',head:true}).in('fpl_id',playerIds):{count:0,error:null};if(countError)throw countError;const statPages=await Promise.all(Array.from({length:Math.ceil((count||0)/1000)},(_,page)=>db.from('fpl_fixture_player_stats').select('fpl_id,gameweek,kickoff_at,points_excluding_bonus,goals,assists,clean_sheets').in('fpl_id',playerIds).range(page*1000,page*1000+999)));const stats=statPages.flatMap(result=>{if(result.error)throw result.error;return result.data||[];});const allStats=stats as FixtureStat[];const selectedOption=period==='week'?(weeks.find(option=>option.key===(key||weeks[weeks.length-1].key))||weeks[weeks.length-1]):period==='month'?(months.find(option=>option.key===(key||months[months.length-1].key))||months[months.length-1]):undefined;const squadById=new Map((squads||[]).map((squad:any)=>[squad.id,squad]));const profileById=new Map((profiles||[]).map((profile:any)=>[profile.id,profile]));const membershipsByPlayer=new Map<number,any[]>();for(const membership of memberships||[]){const list=membershipsByPlayer.get(membership.fpl_id)||[];list.push(membership);membershipsByPlayer.set(membership.fpl_id,list);}const addFixtureStats=(filter:(stat:FixtureStat)=>boolean,includeEmpty:boolean)=>{const totals=new Map<string,any>();for(const stat of allStats){if(!filter(stat))continue;const ownerships=membershipsByPlayer.get(stat.fpl_id)||[];const owner=ownerships.find(member=>new Date(member.acquired_at)<=new Date(stat.kickoff_at)&&(!member.released_at||new Date(member.released_at)>new Date(stat.kickoff_at)))||((stat.kickoff_at>='2025-08-01T00:00:00Z'&&stat.kickoff_at<'2026-06-01T00:00:00Z')?ownerships.find(member=>!member.released_at):undefined);if(!owner)continue;const squad:any=squadById.get(owner.squad_id);if(!squad)continue;const row=totals.get(squad.id)||emptyRow(squad,profileById);row.points+=Number(stat.points_excluding_bonus||0);row.goals+=Number(stat.goals||0);row.assists+=Number(stat.assists||0);row.cleanSheets+=Number(stat.clean_sheets||0);totals.set(squad.id,row);}if(includeEmpty)for(const squad of squads||[])if(!totals.has(squad.id))totals.set(squad.id,emptyRow(squad,profileById));return totals;};
 // Fallback is intentional for the initial 2025/26 backfill: every active player was owned all season.
 if(!allStats.length&&period==='season'){const totals=new Map<string,any>();const playerById=new Map((players||[]).map((player:any)=>[player.fpl_id,player.raw||{}]));for(const [fplId,ownerships] of membershipsByPlayer){const owner=ownerships.find(member=>!member.released_at);const squad:any=owner&&squadById.get(owner.squad_id);const player:any=playerById.get(fplId);if(!squad||!player)continue;const row=totals.get(squad.id)||emptyRow(squad,profileById);row.points+=Number(player.total_points||0)-Number(player.bonus||0);row.goals+=Number(player.goals_scored||0);row.assists+=Number(player.assists||0);row.cleanSheets+=Number(player.clean_sheets||0);totals.set(squad.id,row);}for(const squad of squads||[])if(!totals.has(squad.id))totals.set(squad.id,emptyRow(squad,profileById));return{rows:ranked(totals),periods:{weeks,months},selected:undefined,latestWeek:weeks[weeks.length-1],latestMonth:months[months.length-1]};}
 const seasonTotals=addFixtureStats(()=>true,true);const latestWeek=weeks[weeks.length-1],latestMonth=months[months.length-1],selection=selectedOption||weeks[0];const currentWeek=addFixtureStats(stat=>stat.kickoff_at>=latestWeek.start&&stat.kickoff_at<latestWeek.end,false);const currentMonth=addFixtureStats(stat=>stat.kickoff_at>=latestMonth.start&&stat.kickoff_at<latestMonth.end,false);for(const [id,row] of seasonTotals){row.weekPoints=currentWeek.get(id)?.points||0;row.monthPoints=currentMonth.get(id)?.points||0;}const filtered=period==='season'?seasonTotals:addFixtureStats(stat=>stat.kickoff_at>=selection.start&&stat.kickoff_at<selection.end,true);const fixtureRows=ranked(filtered);if(period==='season'){const totals=new Map<string,any>();const playerById=new Map((players||[]).map((player:any)=>[player.fpl_id,player.raw||{}]));for(const [fplId,ownerships] of membershipsByPlayer){const owner=ownerships.find(member=>!member.released_at);const squad:any=owner&&squadById.get(owner.squad_id);const player:any=playerById.get(fplId);if(!squad||!player)continue;const row=totals.get(squad.id)||emptyRow(squad,profileById);row.points+=Number(player.total_points||0)-Number(player.bonus||0);row.goals+=Number(player.goals_scored||0);row.assists+=Number(player.assists||0);row.cleanSheets+=Number(player.clean_sheets||0);totals.set(squad.id,row);}for(const squad of squads||[])if(!totals.has(squad.id))totals.set(squad.id,emptyRow(squad,profileById));return{rows:ranked(totals),periods:{weeks,months},selected:undefined,latestWeek,latestMonth};}return{rows:fixtureRows,periods:{weeks,months},selected:selectedOption?.key,latestWeek,latestMonth};}
