'use client';

import { AppShell } from '@/components/app-shell';
import { FormEvent, useEffect, useState } from 'react';
import { Save } from 'lucide-react';
import { supabaseBrowser } from '@/lib/supabase-browser';

type Row = { id:string; fplId:number; name:string; team:string; position:string; price:string; originalPrice:string; replacement:string; effectiveDate:string };
type Option = { id:number; label:string };
const today = () => new Date().toISOString().slice(0, 10);

export default function ManagerSquadEditor({ params }: { params: { managerId:string } }) {
  const [rows, setRows] = useState<Row[]>([]), [options, setOptions] = useState<Option[]>([]), [title, setTitle] = useState(''), [message, setMessage] = useState(''), [loading, setLoading] = useState(true), [saving, setSaving] = useState(false);
  async function headers() { const { data:{ session } } = await supabaseBrowser().auth.getSession(); return { Authorization:`Bearer ${session?.access_token || ''}` }; }
  async function loadPlayers() { const response = await fetch('/api/players', { cache:'no-store' }); const data = await response.json(); setOptions((data.players || []).map((player:any) => ({ id:player.id, label:`${player.fullName} · ${player.team} (${player.position})` }))); }
  async function load() { setLoading(true); setMessage(''); const response = await fetch(`/api/admin/manager-squad/${params.managerId}`, { headers:await headers(), cache:'no-store' }); const data = await response.json(); setLoading(false); if (!response.ok) { setMessage(data.error || 'Unable to load squad.'); return; } const squad = data.squad; setTitle(`${squad.profiles?.display_name || 'Manager'} · ${squad.name}`); const positionOrder:Record<string,number> = { GK:1, DEF:2, MID:3, FWD:4 }; setRows((squad.squad_players || []).filter((row:any) => !row.released_at).map((row:any) => { const player = Array.isArray(row.fpl_players) ? row.fpl_players[0] : row.fpl_players; const price = (row.purchase_price / 10).toFixed(1); return { id:row.id, fplId:row.fpl_id, name:player?.web_name || '', team:player?.team_name || '', position:player?.position || '', price, originalPrice:price, replacement:'', effectiveDate:today() }; }).sort((a:Row,b:Row) => (positionOrder[a.position] || 9) - (positionOrder[b.position] || 9) || a.name.localeCompare(b.name))); }
  useEffect(() => { loadPlayers(); load(); }, []);
  async function save(event:FormEvent) { event.preventDefault(); const labels = new Map(options.map(option => [option.label, option.id])); const invalid = rows.find(row => row.replacement && !labels.has(row.replacement)); if (invalid) { setMessage(`Choose ${invalid.replacement} from the replacement lookup list.`); return; } const changes = rows.filter(row => row.replacement || row.price !== row.originalPrice).map(row => ({ squadPlayerId:row.id, price:Math.round(Number(row.price) * 10), replacementFplId:row.replacement ? labels.get(row.replacement) : undefined, effectiveDate:row.effectiveDate })); if (!changes.length) { setMessage('Make a price or replacement change before submitting.'); return; } setSaving(true); const response = await fetch(`/api/admin/manager-squad/${params.managerId}`, { method:'PATCH', headers:{ 'Content-Type':'application/json', ...(await headers()) }, body:JSON.stringify({ changes }) }); const data = await response.json(); setSaving(false); setMessage(response.ok ? `Squad saved. £${(data.budget / 10).toFixed(1)}m remains.` : data.error || 'Unable to save changes.'); if (response.ok) load(); }
  return <AppShell><section className="page-heading"><p className="eyebrow">Commissioner squad editor</p><h1>{title || 'Manager squad'}</h1><p className="sub">Set the date a replacement takes effect. Fixture points before that date stay with the outgoing player.</p></section>{loading ? <p className="helper">Loading squad…</p> : message && !rows.length ? <p className="form-error">{message}</p> : <section className="panel squad-editor"><form onSubmit={save}><datalist id="replacement-players">{options.map(option => <option key={option.id} value={option.label}/>)}</datalist><div className="squad-editor-head"><span>Current squad</span><span>Price paid (£m)</span><span>Possible replacement</span><span>Swap date</span></div>{rows.map((row,index) => <div className="squad-editor-row" key={row.id}><div><strong>{row.name}</strong><small>{row.team} · {row.position}</small></div><input required min="0" step="0.1" type="number" value={row.price} onChange={event => setRows(items => items.map((item,i) => i === index ? { ...item, price:event.target.value } : item))}/><input list="replacement-players" value={row.replacement} onChange={event => setRows(items => items.map((item,i) => i === index ? { ...item, replacement:event.target.value } : item))} placeholder="Leave blank to keep player"/><input aria-label={`Swap date for ${row.name}`} type="date" max={today()} value={row.effectiveDate} onChange={event => setRows(items => items.map((item,i) => i === index ? { ...item, effectiveDate:event.target.value } : item))}/></div>)}<button className="primary" disabled={saving}>{saving ? 'Saving…' : <><Save size={16}/> Submit amendments</>}</button>{message && <p className={message.startsWith('Squad saved') ? 'success' : 'form-error'}>{message}</p>}</form></section>}</AppShell>;
}
