'use client';

import { AppShell } from '@/components/app-shell';
import { Download, Search } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';

type Player = { id:number; name:string; team:string; teamCode:string; position:string; owner:string|null; price:number; points:number; weeklyScores:Record<string, number>; starts:number; substituteAppearances:number; cleanSheets:number; partialCleanSheets:number; assists:number; goals:number; tackles:number; saves:number; goalsConceded:number; yellowCards:number; redCards:number; penaltiesMissed:number; penaltiesSaved:number; ownGoals:number };
const columns: { key:keyof Player; label:string }[] = [
  { key:'starts', label:'Starts' }, { key:'substituteAppearances', label:'Sub apps' }, { key:'goals', label:'G' }, { key:'assists', label:'A' }, { key:'cleanSheets', label:'Full CS' }, { key:'partialCleanSheets', label:'Part CS' }, { key:'saves', label:'Saves' }, { key:'goalsConceded', label:'GC' }, { key:'tackles', label:'Tkl' }, { key:'yellowCards', label:'YC' }, { key:'redCards', label:'RC' }, { key:'penaltiesMissed', label:'Pen miss' }, { key:'penaltiesSaved', label:'Pen saved' }, { key:'ownGoals', label:'OG' },
];
const positionOrder: Record<string, number> = { GK:1, DEF:2, MID:3, FWD:4 };

export default function TffStatsPage() {
  const [players, setPlayers] = useState<Player[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState(''), [search, setSearch] = useState(''), [position, setPosition] = useState('All'), [club, setClub] = useState('All'), [ownership, setOwnership] = useState('All'), [sort, setSort] = useState<keyof Player>('points');
  useEffect(() => { fetch('/api/tff-players').then(async response => { const data = await response.json(); if (!response.ok) throw new Error(data.error); setPlayers(data.players || []); }).catch(reason => setError(reason.message || 'Unable to load the TFF player list.')).finally(() => setLoading(false)); }, []);
  const clubs = useMemo(() => [...new Set(players.map(player => player.team).filter(Boolean))].sort((a, b) => a.localeCompare(b)), [players]);
  const managers = useMemo(() => [...new Set(players.map(player => player.owner).filter((owner):owner is string => Boolean(owner)))].sort((a, b) => a.localeCompare(b)), [players]);
  const filtered = useMemo(() => players.filter(player => (position === 'All' || player.position === position) && (club === 'All' || player.team === club) && (ownership === 'All' || (ownership === 'Available' ? !player.owner : player.owner === ownership)) && `${player.name} ${player.team} ${player.owner || 'Available'}`.toLowerCase().includes(search.toLowerCase())).sort((a, b) => (sort === 'position' ? positionOrder[a.position] - positionOrder[b.position] : Number(b[sort]) - Number(a[sort])) || a.name.localeCompare(b.name)), [players, search, position, club, ownership, sort]);
  return <AppShell>
    <section className="page-heading"><div><p className="eyebrow">Premier League player data - 2025/26</p><h1>2025/26 player scores.</h1><a className="excel-link" href="/api/tff-players/export"><Download size={16}/> Excel format</a></div></section>
    <section className="filters"><label><Search size={18}/><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search players, teams or managers"/></label><div className="selects"><select value={position} onChange={event => setPosition(event.target.value)}><option value="All">All Positions</option><option>GK</option><option>DEF</option><option>MID</option><option>FWD</option></select><select value={club} onChange={event => setClub(event.target.value)}><option value="All">All Teams</option>{clubs.map(team => <option key={team}>{team}</option>)}</select><select aria-label="Ownership" value={ownership} onChange={event => setOwnership(event.target.value)}><option value="All">Ownership</option><option>Available</option>{managers.map(manager => <option key={manager}>{manager}</option>)}</select></div></section>
    <section className="panel player-table player-market">{loading ? <p className="table-message">Loading 2025/26 player scores...</p> : error ? <p className="form-error">{error}</p> : <div className="market-scroll"><div className="market-head tff-market-head"><span>Player</span><button onClick={() => setSort('position')} className={sort === 'position' ? 'sorted' : ''}>Pos.</button><span>Ownership</span><button onClick={() => setSort('points')} className={sort === 'points' ? 'sorted' : ''}>Pts</button><span>25/26 price</span>{columns.map(column => <button key={column.key} onClick={() => setSort(column.key)} className={sort === column.key ? 'sorted' : ''}>{column.label}</button>)}</div>{filtered.map(player => <div className="market-row tff-market-row" key={player.id}><div><strong>{player.name}</strong><small>{player.teamCode || player.team}</small></div><span className={`position-chip ${player.position.toLowerCase()}`}>{player.position}</span><span className={player.owner ? 'owner' : 'available'}>{player.owner || 'Available'}</span><strong>{player.points}</strong><span>&pound;{(player.price / 1000000).toFixed(1)}m</span>{columns.map(column => <strong key={column.key}>{player[column.key] as number}</strong>)}</div>)}</div>}</section>
  </AppShell>;
}