'use client';

import { AppShell } from '@/components/app-shell';
import { Trophy } from 'lucide-react';

export default function CupPage() {
  return <AppShell>
    <section className="page-heading">
      <p className="eyebrow">Head-to-head competition</p>
      <h1>Cup.</h1>
    </section>
    <section className="panel cup-coming-soon">
      <Trophy size={28}/>
      <div>
        <h2>COMING SOON</h2>
        <p className="sub">The cup competitions will be generated by the commissioner midway through the 2026/27 season.</p>
      </div>
    </section>
  </AppShell>;
}
