'use client';
import { AppShell } from '@/components/app-shell';
import { useEffect, useState } from 'react';
import { supabaseBrowser } from '@/lib/supabase-browser';

export default function CupPage(){
 const [data,setData]=useState<any>(null),[snapshot,setSnapshot]=useState<any[]>([]),[active,setActive]=useState(0),[admin,setAdmin]=useState(false),[message,setMessage]=useState('');
 const load=()=>fetch('/api/cups',{cache:'no-store'}).then(r=>r.json()).then(setData);
 useEffect(()=>{load();fetch('/api/cups/snapshot',{cache:'no-store'}).then(r=>r.json()).then(x=>setSnapshot(x.rows||[]));supabaseBrowser().auth.getSession().then(async({data:{session}})=>{if(!session)return;const r=await fetch('/api/me',{headers:{Authorization:`Bearer ${session.access_token}`}});const x=await r.json();setAdmin(Boolean(x.user?.isAdmin));});},[]);
 async function changeDate(id:string,date:string){const {data:{session}}=await supabaseBrowser().auth.getSession();const r=await fetch('/api/cups',{method:'PATCH',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session?.access_token||''}`},body:JSON.stringify({fixtureId:id,date})});const x=await r.json();setMessage(r.ok?'Fixture date saved.':x.error);if(r.ok)load();}
 const divisions=data?.divisions||[],division=divisions[active];
 return <AppShell><section className="page-heading"><p className="eyebrow">Head-to-head competition</p><h1>Cup.</h1></section>{!data?<p className="helper">Loading cups…</p>:!data.cup?<section className="panel"><h2>COMING SOON</h2><p className="sub">The commissioner has not generated the mini leagues yet.</p></section>:<><div className="score-links">{divisions.map((item:any,index:number)=><button className="table-link" key={item.id} onClick={()=>setActive(index)}>{item.name}</button>)}</div><section className="panel period-scores"><p className="eyebrow">{division.name}</p><h2>Mini-league table</h2><div className="period-table-head"><span>#</span><span>Team</span><span>P</span><span>W</span><span>D</span><span>GD</span><span>Pts</span></div>{division.table.map((row:any,index:number)=><div className="period-score-row" key={row.squadId}><b>{index+1}</b><div><strong>{row.team}</strong><small>{row.manager}</small></div><span>{row.played}</span><span>{row.wins}</span><span>{row.draws}</span><span>{row.for-row.against}</span><strong>{row.points}</strong></div>)}{division.playoff&&<p className="helper">Top two qualify for a play-off to decide the winner.</p>}<h2>Fixtures & results</h2>{division.fixtures.sort((a:any,b:any)=>a.round_number-b.round_number).map((fixture:any)=>{const home=division.entries.find((entry:any)=>entry.squad_id===fixture.home_squad_id),away=division.entries.find((entry:any)=>entry.squad_id===fixture.away_squad_id);return <div className="cup-fixture" key={fixture.id}><span>Round {fixture.round_number}</span><strong>{home?.team} {fixture.score.home} – {fixture.score.away} {away?.team}</strong>{admin?<input type="date" value={fixture.starts_at.slice(0,10)} onChange={event=>changeDate(fixture.id,event.target.value)}/>:<small>{new Date(fixture.starts_at).toLocaleDateString('en-GB',{day:'numeric',month:'short'})}</small>}</div>;})}<h2>January 1 seeding snapshot</h2><p className="sub">Full league table at 00:30 GMT. Highlighted teams were placed into {division.name}.</p><div className="period-table-head"><span>Pos</span><span>Team</span><span>Pts</span><span></span><span></span><span></span><span></span></div>{snapshot.map((row:any)=><div className={`period-score-row ${division.entries.some((entry:any)=>entry.squad_id===row.id)?'leader':''}`} key={row.id}><b>{row.rank}</b><div><strong>{row.team}</strong><small>{row.manager}</small></div><strong>{row.points}</strong><span></span><span></span><span></span><span></span></div>)}</section>{message&&<p className="success">{message}</p>}</>}</AppShell>;
}
